### ISSUE TITLE
Please add an appimage file

### ISSUE THREAD

**Issue by Kommynct** [Zelda64Recomp/Zelda64Recomp#21]
An appimage is much more akin to a .exe file and will automatically run with just a double click without creating any clutter/needing dependencies installed.

Flatpak would also be good!

**Comment by Mr-Wiseguy** [comment]
Thanks for the suggestion! I'm planning on providing either a flatpak or appimage in the future, just didn't have the time to learn how to set one up before release. Additionally, build instructions will be available soon (just need to do some cleanup on the recompiler tool to make it easier to use first) which should help with getting it running on other Linux distros in the meantime.

**Comment by eaglewin64** [comment]
I think using a Flatpak would be better because it works on more Linux systems, even ones like Alpine Linux that don't use glibc.

**Comment by yllekz** [comment]
Where does the appimage save data? I want to import my save file from the not-appimage version.

**Comment by Reonu** [comment]
> Where does the appimage save data? I want to import my save file from the not-appimage version.

Same location as the non-appimage version (`~/.config/Zelda64Recompiled`). If you open the appimage version your save will still be recognized, you don't need to do anything.
