### ISSUE TITLE
Windows download link not working

### ISSUE THREAD

**Issue by AngryScotsmanGaming** [Zelda64Recomp/Zelda64Recomp#278]
Hi love your work but your latest update the windows link is not working takes you to a page something to do with an XML

**Comment by MultiKoopa** [comment]
Same issue. Other people are saying the Windows release doesn't even show up for them, just 3 Assets. ???

**Comment by Reonu** [comment]
Hello, we just fixed this, it was a GitHub bug. Try again now. Sorry.

**Comment by MultiKoopa** [comment]
> Hello, we just fixed this, it was a GitHub bug. Try again now. Sorry.

I'm not sure you did.

![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/30543543/02004743-d402-4ca9-acbc-789e8bf73580)

**Comment by Reonu** [comment]
Yes we did. Refresh the page. Thanks.

**Comment by AngryScotsmanGaming** [comment]
I can assure you it is I just downloaded try refreshing the page!

**Comment by MultiKoopa** [comment]
browser glitch I guess. thank you!
