### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Aniconomics** [Zelda64Recomp/Zelda64Recomp#509]
**Describe the bug**

I click on the exe file. The home screen appears with no issue. I click the start button and I am greeted with a black screen that closes itself after 10-20 seconds. Its much faster if I deselect the game window.

**Steps to reproduce the behavior:**

    Click 'Start Game'
    
   **Screenshots**
   
![Capture](https://github.com/user-attachments/assets/3cc483df-313f-4419-82ed-b1ce83b8199a)

   

**Desktop (please complete the following information):**

    OS: Windows 10 Home
    Version: 10.0.19045 Build 1904
    CPU: AMD A6-7310  APU with AMD Radeon A4 Graphics
    GPU: No clue
    
    **Additional context**
My drivers are fully updated. I also have NVIDIA drivers installed. My OS is up to date as well. I assume I downloaded the correct rom, I received no error message.

**Comment by Aniconomics** [comment]
I went directly to the website and installed the latest AMD driver. "AMD Chipset Software v6.10.17.152"
I also used DDU and removed NVIDIA. Then Restarted my computer. 
The problem only got worse. The exe file directly opens to a black screen and crashes.

If you have no solutions. I will try out the mod build.

**Comment by Mr-Wiseguy** [comment]
Go ahead and try the mod build then. If that doesn't work, then go to the game's appdata folder and edit the graphics.json file. Change the line that says `"api_option": "Auto"` to `"api_option": "Vulkan"` and see if that works. Some EOL'd drivers only work properly with D3D12 (the default) and others only work properly with Vulkan, so it's worth a shot.

**Comment by Mr-Wiseguy** [comment]
Event viewer is not useful here. Did you try the mod build and vulkan yet?

**Comment by Mr-Wiseguy** [comment]
Also, do you have the latest visual C++ redistributable installed? The one from this link: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by Aniconomics** [comment]
Installed the full list of redistributables from r/piracy. I'm covered 

I downloaded the modded build 
Created the mod folder in the specified file directory "C:\Users\Anon\AppData\Local\Zelda64Recompiled\mods"
Then downloaded and placed the rtz files in the mod folder

The screen is still black after clicking start game.

**Comment by Mr-Wiseguy** [comment]
This project does not condone piracy, I won't offer support for issues you've run into. Also a word of advice, downloading software from a forum like that when you can just get it from Microsoft's site is an awful idea.
